apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
spec:
  selector:
    matchLabels:
      app: debian
  replicas: 1
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
        - name: debian
          image: debian
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo keep-alive-hack; sleep 10;done"]