# https://github.com/FINCTIVE/http-test
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-test
spec:
  selector:
    matchLabels:
      app: http-test
  replicas: 1
  template:
    metadata:
      labels:
        app: http-test
    spec:
      containers:
        - name: http-test
          image: finctive/http-test
          ports:
            - containerPort: 80
          env:
            - name: Port
              value: "80"
            - name: Message
              value: "test!!!"