# https://github.com/FINCTIVE/dotfiles
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: finctive/playground
          ports:
            - containerPort: 4000